#!/bin/bash
# Config for when running from the source directory.

basedir=$(cd -L $(dirname $0) >/dev/null 2>&1 && pwd -L)

echo 'pottery_bin_dir="'"${basedir}"'"'
echo 'pottery_template_dir="'"${basedir}"'"'
