#!/bin/bash
set -e
eval "$($(dirname $0)/pottery-config)"

## usage: pottery post [-t TIME] [TEXT ...]
##
## Options:
##
## -t TIME The date and time of the event, specified in UTC with format 
##         YYYY-MM-DDThh:mm:ssZ
## 
## Creates a new entry in the project history for the current date and time.
## 
## If no TEXT is given, the entry is opened in the editor specified by the 
## VISUAL or EDITOR environment variable (VISUAL is preferred; EDITOR is 
## used if VISUAL is not set).  After editing, the path to the new file
## is output to stdout, so the command can be used in scripts.
##
## E.g. to create a new entry and input the text in a text editor.
##
##     pottery post
##
## E.g. to create a new entry with the given text:
##
##     pottery post Alice has joined the project.
##
## E.g. to create a new entry with a specified date and time:
##
##     pottery post -d 2018-08-23T13:42:00T We now do trunk-based development instead of pull requests
##


while getopts t: arg
do
    case "$arg" in
        t)
            date_time="$OPTARG"
            ;;
        --)
            break
            ;;
        *)
            echo "Not implemented: $arg" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z $date_time ]
then
	date_time=${TEST_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}
fi

date_y=${date_time:0:4}
date_ym=${date_time:0:7}

text="$*"

rootdir=$("$pottery_bin_dir/_pottery_dir")
dstdir=$rootdir/$date_y/$date_ym
unique_id=$(head -c 12 /dev/urandom | base64)
dstfile=$dstdir/${date_time}_post_${unique_id}.md

mkdir -p $dstdir

echo "$text" > $dstfile
if [ -z "$text" ]
then
	${VISUAL:-${EDITOR:-true}} $dstfile
fi
echo $dstfile
